# Generated by Django 2.2.11 on 2020-03-17 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('href', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abstractText', models.TextField(blank=True, default=None, null=True)),
                ('start', models.DateField(blank=True, default=None, null=True)),
                ('end', models.DateField(blank=True, default=None, null=True)),
                ('created', models.DateField(blank=True, default=None, null=True)),
                ('updated', models.DateField(blank=True, default=None, null=True)),
                ('grantCategory', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('leadFunder', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField(default=datetime.datetime.now)),
                ('n_comments', models.IntegerField(blank=True, null=True)),
                ('n_pingbacks', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('authors', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='rap.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap.Blog')),
            ],
        ),
    ]
