# Generated by Django 2.2.11 on 2020-03-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0002_hecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HECategory',
            new_name='GTRCategory',
        ),
    ]
