# Generated by Django 2.2.11 on 2020-03-17 15:40

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0003_auto_20200317_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='HECategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HEResearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gtrs', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='rap.GTRCategory')),
                ('hecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap.HECategory')),
            ],
        ),
    ]
