# Generated by Django 2.2.11 on 2020-03-17 16:14

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0004_hecategory_heresearcharea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heresearcharea',
            name='gtrs',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rap.GTRCategory'),
        ),
    ]
