# Generated by Django 2.2.11 on 2020-03-18 13:15

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0006_auto_20200317_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('firstName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('otherNames', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('surname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('orchidID', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='grantCategory',
            new_name='projectCategory',
        ),
        migrations.AddField(
            model_name='gtrcategory',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='GTRProjectUrl',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='awardPounds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expenditurePounds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gtrs',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rap.GTRCategory'),
        ),
        migrations.AlterField(
            model_name='gtrcategory',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hecategory',
            name='search_terms',
            field=models.TextField(blank=True, default=None, help_text="These comma separated terms will searched for in projects. You don't need to add the Name", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='leadOrganisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rap.Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rap.Person'),
            preserve_default=False,
        ),
    ]
