# Generated by Django 2.2.11 on 2020-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0007_auto_20200318_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtrcategory',
            name='isHECategory',
            field=models.BooleanField(default=True),
        ),
    ]
