# Generated by Django 2.2.11 on 2020-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0008_gtrcategory_ishecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtrcategory',
            name='sid',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gtrcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gtrcategory',
            name='isHECategory',
            field=models.BooleanField(default=False),
        ),
    ]
